React/Views/RCTTVView.m

In version 0.59 somehow the `[(RCTRootView *)rootview setReactPreferredFocusedView:self];` line was removed. This caused broke the behaviour of setting the focus to a view.
We are working on an app, and the delay caused all sorts of weird behaviour. We patched this in our version and it's working. I made a PR to the core repo at the time, but nobody knew why the delay was there. And in the end it didn't get merged.
* Fixed broken functionality when you try to set the `hasTVPreferredFocus` through `nativeProps` or `updateView`
* Removed delay in `setHasTVPreferredFocus`
We have this code running in our app. And for us it's working out.

Bugfix: RCTTVView patches

---

template/App.js
template/ios/Podfile
template/package.json

Fix issue #5 (react-native init project doesn't compile for tvOS in 0.60.4-1.  In 0.60, projects created with `react-native init` use Cocoapods, and the template files were not adjusted appropriately.
The changes in this PR allow the `-tvOS` target to compile.  They have the effect of breaking the iOS target.  I will be working on a way to support both targets in the template file, but don't yet have a clean solution for that.
Tested this locally and the changes look good.  Will test against the tvos-v0.60.4 branch before doing a patch release.

Fix react-native init template files for tvOS

---

README.md

The motivation for this small change was to help other developers like me avoid confusion when reading the documentation. I did not realize that the master branch was not up to date with the most recent tvOS changes. For example I was looking to test a tvOS sample on the RNTester app. I wanted to verify the TVMenuControl behaved as I needed. But I had mistakenly tested the RNTester app within the master branch which did not have the TVMenuControl module. I realized shortly after that I needed to install the RNTester app that was within the tvos-v0.60.4 branch. 
Thanks for maintaining this repo <3.

Update to the readme to help direct other developers to the tvOS branch. 

---

README.md

Both me and a colleague seperately tried to use react-native-tvos, and both went into the same pitfall of installing react-native globally. And it seems to be a easy pitfall to fall into, as found out after a bit of googling.
Internal Added - Updated README.md to inform about a common pitfall.
No code changes, only documentation.

Add information in README.md about common pitfall

---

Libraries/Text/TextInput/RCTBaseTextInputView.m

Issues with dictation cutoff on iOS were fixed in React Native core in https://github.com/facebook/react-native/pull/19687 and https://github.com/facebook/react-native/pull/18456.
However, these fixes don't work for tvOS.  Best solution for now is to add to the fixes from the above PRs a new condition, where tvOS always tests for the underlying string equality not the attributed string equality.
Tested with a real tvOS 13.3 device.

Quick fix for dictation cutoff in tvOS TextInput component

---

React/Views/RCTTVView.h
React/Views/RCTTVView.m

**The motivation behind the refactor of focus, blur, & select events**
Currently, select, focus, blur events for a view are broadcasted via TVRemoteHandler Module, which I have experienced to be a major source of frame drops in our app when the number of touchable elements on the screen increases. I have instead subclassed RCTTVView in our app which uses RCTDirectEventBlock to send events to the view.
**The motivation behind the refactors of parallax animation.**
In our app, there are scenarios where the blur event of a touchable element is not called to remove the parallax effects but instead, another focus event is called thereby adding another parallax effect in addition to the already existing one. thereby increasing the size of the touchable element from normal.
To fix this, in our …

Refactor RCTTVView's event sender and animation to support subclassing

---

Libraries/Components/AppleTV/TVFocusGuideView.js
RNTester/js/examples/TVFocusGuide/TVFocusGuideExample.js
React/Views/RCTTVFocusGuideView.m

- In 0.62.2, the TVFocusGuideExample in RNTester is not working correctly.  Debugging showed that the destinations prop of the focus guide was being updated too late.  This is fixed by native changes that implement a custom setter for the prop in native.
- The native implementation requires a wrapper view for the focus guide to use in setting its layout.  This PR includes changes to TVFocusGuideView.js to add a wrapper view, so app developers are no longer required to do this.  It also allows the focus guide view to wrap child components, so that the guide can direct navigation from outside to a particular focusable child component.
Tested with the RNTester TVFocusGuideExample

TVFocusGuideView improvements for 0.62.2

---

Libraries/Components/AppleTV/useTVEventHandler.js
README.md
RNTester/js/examples/TVEventHandler/TVEventHandlerExample.js
index.js

Add a `useEffect()` wrapper to make the `TVEventHandler` easier to use.
New test code added to RNTester to show how the feature is used.

useTVEventHandler()

---

RNTester/js/components/RNTesterExampleList.js
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java

Signed-off-by: Ventsislav Dimitrov <4097884+vdmtrv@users.noreply.github.com>
Selecting an Android TV text input doesn't open the soft keyboard.
(This is merged from the original commit on the 0.62 release branch)
[Android TV] [FIXED] - Open soft keyboard upon selecting a text input
* Create a simple view with a text input
* Attempt to enter text in the input
* Soft keyboard should appear and allow the user to enter desired text

fix: Android TV text inputs functionality

---

Libraries/Components/TextInput/TextInput.js

- Disables multiline TextInput for tvOS (the native OS does not support it), so that the text input will actually function on tvOS (#109 )
- Adds a `warnOnce()` call if user tries to use multiline on tvOS
Tested on a tvOS device.

Disable multiline TextInput for tvOS (#109)

---

README.md
package.json
tvos-types.d.ts

Continuation and fix of #102 
[General] [Fixed] - Working typescript extension
Run `yarn tsc` after following guide in `README.md`

fix: hacky type extension import

---

package.json

#102 and #119 PRs added the TypeScript definitions, but the `tvos-types.d` file is not included in the `package.json` and therefore missing after the package installation. This fix includes the `tvos-types.d` in the `files` section of the `package.json`.
[General] [Fixed] - Included the `tvos-types.d` in the `files` section of the `package.json`.
- Install the package `"react-native": "npm:react-native-tvos@latest"`.
- The `tvos-types.d` should be included in the `node_modules/reat-native` directory.

fix: included the tvos-types.d in the package.json

---

Libraries/Components/AppleTV/TVFocusGuideView.js
Libraries/Components/View/ViewPropTypes.js
README.md
RNTester/Podfile.lock
RNTester/js/examples/DirectionalNextFocus/DirectionalNextFocusExample.js
RNTester/js/utils/RNTesterList.ios.js
React/Views/RCTTVView.h
React/Views/RCTTVView.m
React/Views/RCTViewManager.m
tvos-types.d.ts

I've found android's focus guidance api more powerful, and since it's already there, and possible to implement for iOS (mostly), why not give more options to devs?
[tvOS] [FEAT] - Add directional next focus targetability
- create 3 views below each other
- target the next one on `nextFocusRight`
- observe the one below getting focus

feat: nextFocus for iOS

---

Libraries/Components/TextInput/TextInput.js
RNTester/Podfile
RNTester/Podfile.lock
package.json
template/ios/Podfile
tvos-types.d.ts

The `react-native-tvos` repo has been moved out of https://github.com/react-native-community/, and into its own dedicated Github organization https://github.com/react-native-tvos.
Accordingly, some changes need to be made in the files, particularly in `package.json`, Podfile, template.
For more context around this move, see https://github.com/react-native-community/discussions-and-proposals/blob/master/partners/0002-apply-organization-repository-policy.md

Fix repo references after repo move

---

Libraries/Components/AppleTV/useTVEventHandler.js
Libraries/Components/Pressable/Pressable.js
README.md
RNTester/js/examples/Pressable/PressableExample.js
RNTester/js/examples/TVEventHandler/TVEventHandlerExample.js
RNTester/js/utils/RNTesterList.android.js
React/Views/RCTTVView.m
ReactAndroid/src/main/java/com/facebook/react/ReactAndroidHWInputDeviceHelper.java

Allow `Pressable` to be functional on Apple TV and Android TV.  Fixes #125 .
- add `focusable` and `isTVSelectable` view props
- add `onFocus()` and `onBlur()`
- export `focused` as a component state as well as `pressed`
- fire `onLongPress()` when Apple TV remote select button gets a long press
Added examples and made changes in `PressableExample` in RNTester.

Pressable support for TV

---

ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactHorizontalScrollViewManager.java

Fix horizontal scroll view scrolling using DPad even when scrollEnabled is set to false
A scrollview with the scrollEnabled prop set to false still scrolls on tv remote dpad input on androidTV.
This effect can be seen when a Vertical ScrollView with scrollEnabled={false} have multiple HorizontalScrollView with scrollEnabled={false}. When Dpad up down is pressed HorizontalScrollview which is present inside Vertical ScrillView moves like listview.
React Native version:
##0.63.1-2
Expected Results
The scrollview should not scroll when scrollEnabled is set to false, regardless of touch, mouse or DPad input.
This change is continuation of PR  [#25105](https://github.com/facebook/react-native/pull/25105) which had handled scroll events for vertical scroll view but missed to had changes in …

Fix for scrolling issue #128

---

ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java

This fixes the issue where the soft keyboard does not come up on Android TV when a TextInput is focused programmatically (#129).
Tested on an Android TV emulator to verify the fix.

Fix Android TV soft keyboard on TextInput focus (#129)

---

Libraries/Components/Touchable/TouchableOpacity.js

fixes #138
This PR fixes the issue of multiple firing of `onPress` callback on single press on remote on androidTV
Tested on Amazon FireTV and AndroidTV emulator

Fix multiple firing of onPress callback on single press on androidtv remote

---

scripts/react-native-xcode.sh

Apply changes to react-native-xcode.sh script as per changes made under https://github.com/facebook/react-native/pull/29477
This PR reverts the commit number: https://github.com/react-native-tvos/react-native-tvos/commit/a8e85026cfa60056b1bcbcd39cde789e4d65f9cb
This code was already reverted from RN under https://github.com/facebook/react-native/pull/29477 and all details could be found in there.
Thanks to @makarkotlov for the fix
[iOS] [Fixed] - fix "main.jsbundle does not exist" issue

Fix Xcode bundler in staging and release

---

React/Views/ScrollView/RCTScrollView.m

We have a monorepo with two separate apps for iOS and tvOS respectively. `react-native-tvos` is used throughout to avoid hoisting issues. Without this change the build succeeds for the tvOS build, but not for the iOS build because the `RCTTVRemoteHandler.h` is imported regardless of the build target.
[iOS] [Fixed] - RCTScrollView only imports RCTTVRemoteHandler for TV builds
Built the app for iOS without this change: Build failed
Built the app for iOS with this change: Build succeeded
Built the app for tvOS with this change: Build succeeded

Only import RCTTVRemoteHandler in TV builds

---

React/Views/RCTTVFocusGuideView.m

TVFocusGuideView's reactSuperView is nil
I observed that in some cases, in first render, `reactSuperview` of `TVFocusGuideView` is nil which causes and exception with constraint. adding check for nil superview fixes the issue.
[CATEGORY] [TYPE] - Message

Focus guide exception fix

---

Libraries/Components/AppleTV/TVFocusGuideView.js

UI Layout is incorrect whenever we use TVFocusGuideView in tvOS projects. For details, see #216 
The TVFocusGuideView is using two views internally to properly set up the FocusGuide. But the problem is that, if the client specifies any layout related properties in the 'style' prop, TVFocusGuideView will apply the same props to both parent and child views, which is causing the UI issue.
For example, if the client specifies 'marginLeft' property in the style prop, then the TVFocusGuideView will apply the 'marginLeft' for both parent and child, and so, left margin is getting added twice and UI becomes incorrect. The same is applicable for other layout properties.
**React Native version:**
react-native-tvos@0.64.2-2
[tvOS] [Fixed] - Fix UI issue in **TVFocusGuideView**
UI Layout should be …

Fix the issue #216: tvOS - UI Layout is incorrect for TVFocusGuideView.

---

ReactAndroid/src/main/java/com/facebook/react/ReactAndroidHWInputDeviceHelper.java
ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java
ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactAndroidHWInputDeviceHelper.java
ReactAndroid/src/main/java/com/facebook/react/views/modal/BUCK
ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.java

On Android TV, the `Modal` component is rendered in its own view class, not inside `ReactRootView`, so focus events are not handled and sent to the event listener as they are in the root view.
This change fixes that issue (#115), so that buttons inside a modal change appearance as expected when navigated to by the D-pad on Android TV.
Tested with `ModalExample` in the RNTester app.

Android TV: fire focus events in Modals (fix #115)

---

React/Base/RCTRootView.m
React/Base/RCTTVRemoteHandler.h
React/Base/RCTTVRemoteHandler.m
React/Modules/RCTTVMenuBridge.m
React/Views/RCTModalHostView.m

Fix #69 (react-native-navigation issues)
- RCTRootView code to attach TV remote handler is now wrapped inside RCTTVRemoteHandler
- TV remote handler now has global state to track whether menu key should be enabled
- TV remote handler now also listens for TVMenuControl notifications, so views that create a TV event handler no longer have to do anything else
Tested with the unit and integration tests, RNTester manual testing, new project testing, and testing against `react-native-navigation`.

Refactor of RCTTVRemoteHandler

---

ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactAndroidHWInputDeviceHelper.java

Implement the `longSelect` TV remote control event for Android TV (this already exists on Apple TV).
Tested with the RNTester TVEventHandler example.

Implement TV event longSelect for Android (#232)

---

ReactAndroid/src/main/java/com/facebook/react/config/ReactFeatureFlags.java
ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactAndroidHWInputDeviceHelper.java
packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterApplication.java
packages/rn-tester/js/examples/TVEventHandler/TVEventHandlerExample.js
template/android/app/src/main/java/com/helloworld/MainApplication.java

Adding `enableKeyDownEvents` in `ReactFeatureFlags` class.  If this is set in your application startup code, both key down and key up events will be sent to TVEventHandler.  See discussion in related issue #233 . Fixes #251.
Example from template application:
```java
@Override
public void onCreate() {
super.onCreate();
SoLoader.init(this, /* native exopackage */ false);
// Normally we only send key up events in ReactAndroidHWInputDeviceHelper
// Change enableKeyDownEvents to true to send both key down and key up events
ReactFeatureFlags.enableKeyDownEvents = false;
```

Android TV: feature flag for key up events (#233) (#251)

---

Libraries/Components/AppleTV/TVFocusEventHandler.js
Libraries/Components/Pressable/Pressable.js
Libraries/Components/Touchable/Touchable.js
index.js

Each Touchable component needlessly creates own event listener, which, after focus transition, results in multiple handlers called just to check if event should be even handled by particular component. Performance of focus transition can be improved.
[General] [Changed] - Improved focus transition performance of Touchable components by introducing single Event Listener for all Touchables, instead of one Event Listener per Touchable.
I've prepared simple TV app with improvement implemented as a patch to check and measure performance improvement. Rough measurement of focus transition between tiles on AndroidTV emulator indicates that time between onBlur -> onFocus pair reduced from ~11 ms to ~7 ms on average, and peak value form ~48 ms to ~14 ms. …

Implement single event listener for Touchable components to boost performance

---

React/Base/RCTTVRemoteHandler.h
React/Base/RCTTVRemoteHandler.m

This adds support for the Channel Up/Down buttons on the iOS control center remote control.
[TVOS] [Added] - Add support for Channel Up/Down buttons on iOS control center remote control.
Add a TV event handler that logs eventType, open the Apple TV remote on an iPhone and press channel up/down to see the new pageUp/Down events

Add support for Page Up / Page down (channel buttons) on iOS remote control

---

Libraries/Components/AppleTV/tagForComponentOrHandle.js
Libraries/Components/Touchable/TouchableOpacity.js
packages/rn-tester/js/examples/DirectionalNextFocus/DirectionalNextFocusExample.js
packages/rn-tester/js/examples/TVFocusGuide/TVFocusGuideExample.js

At the moment, the nextFocusLeft/Right/Up/Down APIs need React view tags to be passed in, so the app has to use findNodeHandle() to get the tags. This change allows component refs to be passed in directly, and the tags are calculated internally before passing to native layer.  Passing in tags directly will still work, so this is not a breaking change.
This PR also includes:
- Modified `DirectionalNextFocusExample` to demonstrate passing in component refs to nextFocus APIs
- Refactor `DirectionalNextFocusExample` and `TVFocusGuideViewExample` to use modern functional components

Enhancement to the nextFocus APIs for TV

---

tvos-types.d.ts

react-native-tvos adds a "focused" prop to Pressable's callback props (style and children). This PR adds that prop to the type definitions so it can be used in typescript code. 
[General] [Added] - Pressable's focused callback prop types
```tsx
<View>
<Pressable>
{({focused}) => (
<Text
style={tw`${focused ? 'text-red-500 ' : 'text-blue-500 '}`}>
Thing 1
</Text>
)}
</Pressable>
<Pressable>
{({focused}) => (
<Text
style={tw`${focused ? 'text-red-500 ' : 'text-blue-500 '}`}>
Thing 2
</Text>
)}
</Pressable>
<Pressable>
{({focused}) => (
<Text
style={tw`${focused ? 'text-red-500 ' : 'text-blue-500 '}`}>
Thing 3
</Text>
)}
</Pressable>
</View>
```

add focused prop to Pressable API's PressableStateCallbackType

---

tvos-types.d.ts

The TVMenuControl was renamed to TVEventControl & 'pan' events were added
- Remove un-used `HWFocusEvent` since in practise the type-system could only ever reach the "common" event
- Renamed TVMenuContro to TVEventControl
- Added the missing fields for the 'pan' events
- Renamed HWKeyEvent to HWEvent since it contextuelly made more sense based on recent changes

update tvos-types to include pan events

---

Libraries/Components/Touchable/TouchableHighlight.js
React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.h
React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
React/Views/RCTTVView.h
React/Views/RCTTVView.m
packages/rn-tester/js/examples/DirectionalNextFocus/DirectionalNextFocusExample.js

- Adds 1 px thick focus guides when needed... e.g. if `nextFocusRight` is set, place a 1 px thick focus guide on the right of the view, with focus destination set to the value of `nextFocusRight`.
- nextFocus APIs work even without real views in the direction of navigation
- works for both Fabric and non-Fabric
- Corrects missing implementation details in `TouchableHighlight`
- Update DirectionalNextFocus RNTester example

Use focus guides for nextFocus on tvOS (fix #306)

---

Libraries/Components/Touchable/TouchableNativeFeedback.js

See #159
The same issue which happens for `TouchableHighlight` happens also to `TouchableNativeFeedback`.

Prevent extra onPress events in TouchableNativeFeedback

---

Libraries/Components/AppleTV/TVFocusGuideView.js
packages/rn-tester/Podfile.lock
packages/rn-tester/js/components/RNTesterTheme.js
packages/rn-tester/js/examples/TVFocusGuide/TVFocusGuideSafePaddingExample.js
packages/rn-tester/js/utils/RNTesterList.ios.js
tvos-types.d.ts

We are having issues when a TVFocusGuideView has children which edges are the same are the parent. It usually happens when there are no padding on the parent and no margin on the children.
https://user-images.githubusercontent.com/12344434/173606404-1427dc98-453c-401e-81e6-7c8eb222da3f.mov
https://user-images.githubusercontent.com/12344434/173606603-b8be095e-41ab-4d22-9b88-fd8e3b163acf.mov
Added a prop `disableSafePadding?: boolean`. If `true`, it won't add the new style rule `safePadding` on the focus guide's view.
Not sure if its the best way, but right now there is no way to add some styling only to the focus guide view's style.
```ts
import React, { FC, useRef, useState } from 'react';
import {
FlatList,
StyleSheet,
Text,
View,
TouchableOpacity,
findNodeHandle,
TVFocusGuideView, …
```

fix: add default padding to focus guide view to fix focus order with its children

---

ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactAndroidHWInputDeviceHelper.java

Add CHANNEL_UP, CHANNEL_DOWN, and DIGIT (0-9) key event support to Android TV
[Android] [Added] - Add CHANNEL_UP, CHANNEL_DOWN, and DIGIT (0-9) key event support to Android TV
We develop application that utilizes aforementioned events, we've made a build against react-native fork with these changes and it was working as expected. These changes just add more button mappings, so I don't think it requires some extensive testing.

Add CHANNEL_UP, CHANNEL_DOWN, and DIGIT (0-9) key event support to Android TV

---

React/Base/RCTTVRemoteHandler.h
React/Views/RCTModalHostView.h
React/Views/RCTModalHostView.m
React/Views/RCTModalHostViewController.h
React/Views/RCTModalHostViewController.m
packages/rn-tester/js/components/RNTOption.js
packages/rn-tester/js/examples/Modal/ModalOnShow.js

- Use the view controller's `viewDidAppear`, `viewDidDisappear`, etc., to control adding and removing menu key gesture recognizer and RCTTVRemoteHandler
- Clean up unneeded code
- Fix up RNTester ModalExample for TV

Fix issues found with modal TV gesture recognizer and menu key behavior (fix #341)

---

React/Views/RCTModalHostView.m

Fixed an issue where tvRemoteHandler in RCTModalHostView.m was used even when not targeting TvOS, which is not available.

Fixed compilation error with RCTModalHostView.m

---

React/Base/RCTTVRemoteHandler.m

`RCTTVRemoteHandler` setups a lot of gesture handlers over the root view, but those are preventing root's children from recognizing gestures as well.
This happens because remote handler's recognizers have their `cancelsTouchesInView` set to `true` by default, as stated in [Apple's doc](https://developer.apple.com/documentation/uikit/uigesturerecognizer/1624218-cancelstouchesinview):
> When this property is true (the default) and the gesture recognizer recognizes its gesture, the touches of that gesture that are pending aren’t delivered to the view and previously delivered touches are canceled through a [touchesCancelled(_:with:)](https://developer.apple.com/documentation/uikit/uiresponder/1621116-touchescancelled) message sent to the view. If a gesture recognizer doesn’t recognize its …

Fix remote tv handler preventing subviews to recognize gestures

---

Libraries/Components/TV/TVEventControl.js
README.md
React/Base/RCTTVRemoteHandler.h
React/Base/RCTTVRemoteHandler.m
React/Modules/RCTTVMenuBridge.m
packages/rn-tester/js/RNTesterAppShared.js
tvos-types.d.ts

Builds on top of #366 to allow app developers to control whether `RCTTVRemoteHandler`'s gesture recognizers cancel touches (and block other event handlers).

Apple TV: TVEventControl methods for controlling cancelsTouchesInView

---

Libraries/Components/TV/TVFocusGuideView.js
tvos-types.d.ts

- Props not used by container should be forwarded to inner view
- Some styling attributes should be forwarded to innervew. Such as `position` and `opacity`
- New `enabled` prop, it allows to toggle the displayability of the container. Useful for focus guides that don't have children and only redirects to focus to somewhere else.
IMO, this PR should be merged in **0.68.2** as well as the latest version of react-native-tvos since 0.69.x brings changes that might not allow everyone to upgrade.

TVFocusGuide fixes and improvements

---

tvos-types.d.ts

Adding back the typescript types `hasTVPreferredFocus` `tvParallaxProperties` that now has been removed from the react-native main repo.

Update typescript types to support react-native 0.69

---

React/Views/RCTTVView.m

This PR fixes #204.
First of all, it works fine with Fabric because the implementation is different. There are several different problems with Fabric (in particular with TVFocusGuide) which I will create issues and PRs but this is not one of them 😄 
As it's described in the issue, TVFocusGuide doesn't work sometimes, especially on the first renders. If you check `TVFocusGuideExample` in the `RNTester` app, you'll see that it works. So, you might think there's no issue but that's not the reality. The reason is, there's a constant state update going on in that example which covers up the issue by rerendering the app, thus leading to multiple native `_setDestinations` calls which make the example look like it works.
By commenting out …

fix: solve TVFocusGuide first render problem

---

React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm

This PR fixes #421 and fixes #422.
As it is described in #421, every element was getting `UIFocusGuide` attached to it unnecessarily. It was due to the `UIFocusGuide` creation in `initWithFrame` method without any checks. I moved the `UIFocusGuide` creation to `addFocusDestinations` to fix the issue.
The second issue was constant `UIFocusGuide` constraints growth as it is described in #422. The reason was setting constraints in `updateLayoutMetrics` which gets called very often. It was leading to unnecessary constraint definitions. Moved that section to `addFocusDestinations` method as well to fix it.
Here's before (doesn't show the constraints in this SS but you can check #422):
Here's after the fix (even after a couple fast refreshes):
- Build the `RNTester` app (Fabric enabled)
- …

fix: make sure UIFocusGuide is only applied when necessary

---

Libraries/Text/Text.js

Recent changes in the `Text` component make it accessible and pressable by default. On Android TV, this has the side effect of making it focusable. Only controls (`Touchable`, `Pressable`, `TextInput`, etc.) should be focusable.
Fixed by changing `Text.js` so that a `Text` component must explicitly have `accessible={true}` in order to be pressable or focusable on TV platforms.
Fixes #389 .
Tested with the `TVInputDemo` test app, and `RNTester`.

fix: [Android TV] Text should not be accessible by default 

---

React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm

This PR fixes #424.
Focus behavior becomes *very* interesting on tvOS when Fabric is enabled after the first render. This is what I mean:
https://user-images.githubusercontent.com/22980987/210118993-8eef9822-d4b1-4dfa-a130-4e561cd70a47.mov
Even though it makes no sense, focus moves to `Button 4` whenever I try to move the focus up. It doesn't always have the same behavior, though. It is completely random. Sometimes you press `right` it moves up etc. To reproduce this, you just need to trigger a fast refresh once, that's it.
It was really hard to understand what's going on and turned out to be a nasty bug.
| FIRST RENDER | AFTER FAST REFRESH |
|---|---|
| ![Screenshot 2022-12-30 at 20 58 00](https://user-images.githubusercontent.com/22980987/210119145-995247e3-0f07-4e3e-ba35-3ad8e1a61577.pn …

fix: clear TVFocusGuide on view recycling process

---

Libraries/Components/TV/TVFocusGuideView.js
README.md
packages/rn-tester/Podfile.lock
tvos-types.d.ts

Whenever I saw `safePaddings` approach, I thought "okay, this is a good workaround but the focus engine should be deterministic and shouldn't require this sort of workaround". Started digging to get rid of `safePaddings` necessity and found that it is fairly simple and the focus engine indeed works as expected if we prepare the layout in a way that it can do its job.
Here's how it works without the changes in this PR:
<table>
<tr>
<th>OLD ARCH</th>
<th>FABRIC</th>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/22980987/210111757-98a19aa3-5c33-4b8e-84ee-a85b4edcddd7.mov
</td>
<td>
https://user-images.githubusercontent.com/22980987/210110060-80a31215-9fbe-4514-a85e-e0d6cc75ea1c.mov
</td>
</tr>
</table>
This is `TVFocusGuideSafePaddingExample`. The expected behavior is simple. …

feat: make TVFocusGuide work reliably without safePadding

---

Libraries/Components/TV/TVFocusGuideView.js
README.md
tvos-types.d.ts

This PR is almost the same as https://github.com/react-native-tvos/react-native-tvos/pull/426 but that one has been reverted by @douglowder due to a regression on Android.
[This](https://github.com/react-native-tvos/react-native-tvos/commit/507aad608565cff6a5176377de3edb9f496a63fd) fixes the problem on Android by disabling the view flattening on that platform just like we did for iOS.
https://user-images.githubusercontent.com/22980987/211201524-2276d485-1e68-41f4-bc70-3211d7c9ae35.mov

feat: make TVFocusGuide work reliably without safePadding v2

---

Libraries/Components/Touchable/TVTouchable.js

The function is not available on AndroidTV which crashes it, I added an explicit platform check similarly as was done in TouchableNativeFeedback.js (b94c21cfcc869eeb9a5aff852ea856e379d373d4). This fixes #442.
Could you also have a look @maximilize since you introduced this feature?
Thanks!

Fix onLongPress bug AndroidTV

---

ReactCommon/jsi/JSCRuntime.cpp

This fixes #445. JSC features were not detected properly on tvOS. Before this change, tvOS was always handled as if it was iOS 9 - this is the default version set in `Availability.h` on tvOS platform.
**Availability.h**:
```
#ifndef __TV_OS_VERSION_MIN_REQUIRED
#ifdef __ENVIRONMENT_TV_OS_VERSION_MIN_REQUIRED__
/* compiler sets __ENVIRONMENT_TV_OS_VERSION_MIN_REQUIRED__ when -mtvos-version-min is used */
#define __TV_OS_VERSION_MIN_REQUIRED __ENVIRONMENT_TV_OS_VERSION_MIN_REQUIRED__
#define __TV_OS_VERSION_MAX_ALLOWED __TVOS_16_1
/* for compatibility with existing code.  New code should use platform specific checks */
#define __IPHONE_OS_VERSION_MIN_REQUIRED 90000
#endif
#endif
```
Before making the changes in the code, I have checked the features availability here:
- …

Fix JSC features detection on tvOS

---

React/Base/RCTTVRemoteHandler.h
React/Base/RCTTVRemoteHandler.m
ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactAndroidHWInputDeviceHelper.java
tvos-types.d.ts

The detection of a long press in any of the DPad arrows is relevant in different scenarios, for example for fast-forwarding or fast-backward the progress of a video. So, I have added these cases to the `onHWKeyEvent` and named them `longUp/longDown/longLeft/longRight`.
These events can be detected by using the `useTVEventHandler`, for example:
```ts
const myTVEventHandler = useCallback(
(event: HWEvent) => {
switch (event.eventType) {
case 'longUp':
handleLongUp();
break;
case 'longDown':
handleLongDown();
break;
case 'longLeft':
handleLongLeft();
break;
case 'longRight':
handleLongRight();
break;
}
},
[handleLongUp, handleLongDown, handleLongLeft, handleLongRight],
);
useTVEventHandler(myTVEventHandler);
```
I have adjusted `RCTTVRemoteHandler.m` to detect the long press in the DPad …

Detect long up/down/left/right arrow press

---

ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java
ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java

As found out by @wouterds, a change made in the latest `autoFocus` PR made the project collide with `reac-native-screens` library. I described the problem [there](https://github.com/react-native-tvos/react-native-tvos/pull/450#issuecomment-1411934744) but echoing here for better visibility:
> They (react-native-screens) have this `SearchBarView` which extends `ReactViewGroup`. I introduced a public method in `ReactViewGroup` called `setAutoFocus` and they have [this line](https://github.com/software-mansion/react-native-screens/blob/main/android/src/main/java/com/swmansion/rnscreens/SearchBarView.kt#L22) which generates a setter called `setAutoFocus` method I believe (Kotlin magic). It's forbidden to create a method while the extended class has the same, so here we have our problem 😄
This …

chore: rename setAutoFocus public method to prevent naming collisions

---

Libraries/NativeAnimation/RCTNativeAnimatedTurboModule.mm
ReactAndroid/src/main/java/com/facebook/react/animated/EventAnimationDriver.java
ReactAndroid/src/main/java/com/facebook/react/animated/NativeAnimatedModule.java
ReactAndroid/src/main/java/com/facebook/react/animated/NativeAnimatedNodesManager.java
ReactAndroid/src/main/java/com/facebook/react/uimanager/events/Event.java

This issue (https://github.com/facebook/react-native/issues/33375) has been fixed upstream in `react-native` but the commits are not yet in our repository. We're not exactly sure what causes it, but we were able to resolve the issue by cherry-picking those 4 commits related to `NativeAnimatedNodesManager.java` from upstream into `react-native-tvos`.
We did a lot of manual testing and ran automated tests every hour last night, and we can now no longer reproduce it.
Our patched fork with those 4 commits [`@wouterds/react-native-tvos`](https://www.npmjs.com/package/@wouterds/react-native-tvos)
Sentry stacktrace: https://sentry.io/share/issue/d58aa423fa9e4ddebb0a4271533d1590/

Fix: android crash connectAnimatedNodes

---

.circleci/config.yml
Gemfile.lock
Libraries/Core/ReactNativeVersion.js
React/Base/RCTVersion.m
ReactAndroid/gradle.properties
ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
ReactCommon/cxxreact/ReactNativeVersion.h
package.json
template/package.json

Merge from Facebook core 0.69 stable branch.
Includes mitigation fix for Samsung text input issue https://github.com/facebook/react-native/issues/35936 .

Pick up fixes from RN core for 0.69 branch

---

Libraries/Components/TV/TVFocusGuideView.js
Libraries/Lists/VirtualizedList.js
README.md
React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
React/Views/RCTTVView.h
React/Views/RCTTVView.m
React/Views/RCTViewManager.m
ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java
ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java
ReactCommon/react/renderer/components/view/ViewProps.cpp
ReactCommon/react/renderer/components/view/ViewProps.h
packages/rn-tester/js/examples/TVFocusGuide/TVFocusGuideAutoFocusExample.js
tvos-types.d.ts

This PR introduces a new addition to `TVFocusGuide` arsenal, `focusTrap*`. This new functionality allows us to *trap* the focus inside a container. When it's in, we can make sure it stays in until we don't want it to do so.
This concept is well-known and used on the web for a11y. The difference here is though, our implementation allows us to have fine-grained control based on the direction. We can trap the focus in only one direction while allowing it to move freely in other directions. E.g we can trap it for **left** and **right** actions but not for **up** and **down**.
This flexibility is important because the functionality is mainly implemented to fix a focus bug that exists in **VirtualizedList** family (FlatList etc.). I'm not even sure calling it a *bug* is even fair but let me …

feat: add focusTrap functionality to TVFocusGuide

---

ReactAndroid/src/main/java/com/facebook/react/config/ReactFeatureFlags.java
ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactAndroidHWInputDeviceHelper.java
packages/rn-tester/js/examples/TVEventHandler/TVEventHandlerExample.js

Fix #358.
Changes the long press handling to turn on a boolean state when repeated down events are detected from a DPad key, and fire TVRemoteHandler longSelect/Up/Down etc. events while the key is down, instead of waiting for the key up event.
Will do some additional testing of this change before merging.

fix: [Android TV] long presses should fire events promptly

---

ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java
packages/rn-tester/js/examples/TVFocusGuide/TVFocusGuideAutoFocusExample.js

This PR fixes a focus recovery issue mostly related to ScrollView family components (VirtualizedList, FlatList etc. incl.). It is practically one of the missing pieces of the "focus recovery" work that was introduced [in this PR](https://github.com/react-native-tvos/react-native-tvos/pull/450). 
Focus recovery logic wasn't implemented accounting for `removeClippedSubviews` logic but VirtualizedList family components have it `true` by default on Android. It leads to this weird behavior where the focus gets lost when view clipping logic can't keep up with the scrolling speed. It is easily reproducible by calling `.scrollToIndex({ index: 0, animated: false })` on a list. You can see a slight flicker on Android below, after the scroll-to-top action. It is an artifact of …

[ANDROID] fix: recover focus on instant scroll state changes

---

tvos-types.d.ts

Fixes #476.
Fixes a syntax error inside tvOS typescript declaration file. Also enriches `TVFocusGuideView` type.

fix: ts type declarations

---

ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java

The `autoFocus`'s feature one of the primary functionalities is moving focus to the first focusable element on the first visit. I discovered that it was "accidentally" working on most of the cases which made us fail to catch this bug 😄. So, a bug was preventing the `moveFocusToFirstFocusable` function to work properly.
This PR fixes the bug and makes the function move the focus to the first focusable every time.

fix: make moveFocusToFirstFocusable work as intended

---

React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
React/Views/RCTTVView.m
ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java
packages/rn-tester/js/examples/TVFocusGuide/TVFocusGuideAutoFocusExample.js

The focus recovery feature that is introduced in https://github.com/react-native-tvos/react-native-tvos/pull/450 had a bug. `hasTVPreferredFocus` or `requestTVFocus` commands were getting somewhat ignored during the focus recovery process. The implications were different on Android and tvOS. Set up a new test case to demonstrate the problem.
On Android, we detect and start a recovery effort when the focus is getting lost. Upon detection, the focus gets "parked" to the closest `TVFocusGuide` and we postpone the recovery process to the end of the main thread to give UI some time to complete rendering before we decide where the focus should go. The problem is, the focus can move to another item during that small timeframe. Like, one of the elements on the UI can request focus.  We weren't …

fix: restore focus responsibly

---

Libraries/Lists/VirtualizedList.js

When passing `initialScrollIndex` smaller than 0 for example -1 new elements won't render. `_updateCellsToRender` function was checking if `this.props.initialScrollIndex` is truthy and -1 was returning true.
[General] [Fixed] - make sure initialScrollIndex is bigger than 0

fix: make sure initialScrollIndex is bigger than 0

---

Libraries/Components/Touchable/Touchable.js

https://github.com/react-native-tvos/react-native-tvos/commit/76baca940cb92e08c8983ebd2825c3bf00599cdf#diff-7bdf9271d2d608afa4008d7496ccab59ca0e2f4634d21219503dd4e08b329368L12
This change is missing the `ReactNative` import, but it required in [here](https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.71.7/Libraries/Components/Touchable/Touchable.js#LL384C7-L384C7).
[General] [Fixed] - Add missing ReactNative import in Touchable
I'm upgrading react-native-tvos to 0.71 for a project, and it's working fine with this fix (by patch).

Touchable: Add missing ReactNative import

---

Libraries/Components/Touchable/TVTouchable.js

Fix issue #500 by adding a flag to the `TVTouchable` class to ensure that its tvEventHandler code is not called after destroy() is called.
- Test code in #500 should work with no errors.

fix: Remove TVTouchable interference between onPress and unrender

---

template/ios/Podfile

"install! 'cocoapods', :deterministic_uuids => false" lready present in: prepare_react_native_project
This modification is related to the template/ios/Podfile file. It involves removing duplicates in the pod sources used in the file.
[BUG FIX] [Dependency Management] - Remove duplicates in pod sources.

remove duplicate

---

template/ios/HelloWorld-tvOS/Info.plist
template/ios/HelloWorld.xcodeproj/project.pbxproj

https://github.com/react-native-tvos/react-native-tvos/blob/44f74a2d499538c57fcbe6bfd57ba3b60337a81b/template/ios/HelloWorld/Info.plist#L20
The MARKETING_VERSION is missing in the template project.
I also update the `HelloWorld-tvOS/Info.plist` to use MARKETING_VERSION.
It works with an initial project.

Add missing MARKETING_VERSION in template project

---

scripts/cocoapods/flipper.rb
template/ios/Podfile

Fix #521 for enable Flipper for iOS.
react-native-tvos split `React-Core` to `React-Core-iOS` and `React-Core-tvOS`:
I haven't tested with `React-Core-tvOS`, it probably not work.
Confirmed it works with an initial project on iOS:

Add FB_SONARKIT_ENABLED setting for React-Core-iOS

---

template/ios/HelloWorld.xcodeproj/project.pbxproj

When installing a React Native library that contains Swift code to the tvOS target, I get the following error:
```
[!] Unable to determine Swift version for the following pods:
- `MyLib-tvOS` does not specify a Swift version and none of the targets (`MyApp-tvOS`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```
This happens because the `SWIFT_VERSION` build setting is not set on a newly created tvOS target (but it is in the iOS target).
In this PR I add the same setting to the tvOS target to enable devs to use React Native libraries using Swift code straight away.
I could find a few issues on library repositories from users having this issue:
- …

Add swift version in tvOS target in template

---

types/public/ReactNativeTVTypes.d.ts

The `requestTVFocus()` method was overriding the `View` interface in `ReactNativeTVTypes.d.ts`, leading to an error when executing `yarn tsc` in an app built with React Native TV. This change aligns the method type with the other types in `ReactNativeTypes.d.ts`.
Fixes #524 .
Changelog: [General][Fixed] Correct TS type for requestTVFocus()
Tested in an app to ensure that `requestTVFocus()` and other similar methods (e.g. the `focus()` method of `TextInput`) are now all recognized correctly as types by the Typescript compiler.

fix: Correct TS type for requestTVFocus()

---

Libraries/Components/View/View.js

After merging the remote-tracking [commit](https://github.com/react-native-tvos/react-native-tvos/commit/76baca940cb92e08c8983ebd2825c3bf00599cdf), the `requestTVFocus()` method is missing from the referenced object. This issue occurred because the pure `forwardRef` object was passed to the View's `ref` prop instead of using `_setNativeRef`, as defined in commit [#471](https://github.com/react-native-tvos/react-native-tvos/pull/471).
[General] [Fixed] - Reattached `requestTVFocus()` method to View reference object.
Test the **Focus To Side Menu** button in [TVFocusGuideAutoFocusExample](https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.71.11/packages/rn-tester/js/examples/TVFocusGuide/TVFocusGuideAutoFocusExample.js) to ensure it works without any exceptions.

fix: method requestTVFocus is missing after remote-tracking v0.71.6 merge

---

Libraries/LogBox/UI/LogBoxInspector.js

Per discussion, move the footer with "Dismiss" and "Minimize" to the top, so TV user does not have to navigate through all the stack frames to reach these buttons.

Move dismiss/minimize to top of LogBox screen for TV

---

packages/react-native/Libraries/Components/Pressable/Pressable.js
packages/rn-tester/js/components/RNTesterNavbar.js
packages/rn-tester/js/examples/Pressable/PressableExample.js

`Touchable` components are honoring the `disabled` prop and not allowing selection or focus when disabled. However, `Pressable` is ignoring this prop for TV apps.
Made changes to set `isTVSelectable` and `focusable` to false when `disabled` is true.
Added a `console.warn()` to `PressableExample` in `RNTester` if the example disabled component is pressed or selected. Made other improvements to `PressableExample` to make focus changes visible in the example components.

Pressable should honor disabled prop (#550)

---

README-tv.md
packages/react-native/template/package.json

- Align the template scripts with `react-native-template-typescript-tv` and fully use Expo CLI
- README improvements
- Discuss both TV platforms (less Apple TV centric)
- Reorganization
- Remove outdated wording

TV patch 25: template and README fixups

---

packages/react-native/types/public/ReactNativeTVTypes.d.ts

I realized that some of the TV types were a bit broken, we were missing a couple of imports. This PR fixes that.
Also fixes the linting issues cause by `redundant-undefined/redundant-undefined` rule. It basically dictates that every optional  property should explicitly have `undefined` in the type def.

fix: tv types

---

packages/react-native/React-Core.podspec
packages/react-native/React/Base/RCTTouchHandler.m
packages/react-native/React/Base/RCTTouchHandlerTV.m
packages/react-native/React/Fabric/RCTSurfacePointerHandlerTV.mm
packages/react-native/React/Fabric/RCTSurfaceTouchHandlerTV.mm
packages/react-native/React/React-RCTFabric.podspec

- They are not needed for TV
- Fixes #595
The solution is to add TV-specific stub implementations of `RCTTouchHandler`, `RCTSurfacePointerHandler`, and `RCTSurfaceTouchHandler`, and modify podspecs to include the right implementations for phone and TV targets.
[iOS] [Fix] Disable phone touch handlers
- Test release build on real tvOS 17.0 or greater device

fix: Disable phone touch handlers for Apple TV

---

packages/react-native/React/Views/RCTTVView.m

When using the Apple TV remote, swiping down on an interactive button triggers the parallax. But the parallax is reversed for the vertical swipe. Horizontal is correct.
When moving down, the bottom part of the button should come forward. But in the implementation of `react-native-tvos` is reversed and the bottom part of a button is moved backwards.
Correct behavior when swiping down:
https://github.com/react-native-tvos/react-native-tvos/assets/38136/b4a0cb41-ba9e-4d8e-8100-367848d7315f
Inverse the X tilting for the added parallax effect
[FIXED] - Pick one each for the category and type tags (fixes #593)

Fix parallax tilt on X axis being reversed of tvOS default

---

packages/react-native/Libraries/Components/TabBarIOS/RCTTabBarItemNativeComponent.js
packages/react-native/Libraries/Components/TabBarIOS/RCTTabBarNativeComponent.js

Fixed imports in couple of files - 
1. RCTTabBarItemNativeComponent.js
2. RCTTabBarNativeComponent.js
Make use of default exports for requireNativeComponent
Pick one each for the category and type tags:
[INTERNAL] [FIXED] - Fixed import issues in ` RCTTabBarItemNativeComponent.js` and `RCTTabBarNativeComponent.js`
Tested it in tvOS

fix: wrong import made for tabBarIOS

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.java
packages/rn-tester/js/examples/Modal/ModalOnShow.js

On Android, modal views were not sending hardware key events to any TV event handler.
Solution: modal views have their own TV event handler instance to handle their key events.
Fixes #609 
[Android][Fixed] add TV event handler to Android Modal component
Code is added to the Modal example in RNTester to show that the fix works. Without the fix, only focus and blur events are seen in the modal example.

fix: add TV event handler to Android Modal component

---

packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
packages/react-native/React/Views/RCTTVView.m

Add missing gesture recognizer for long presses to Apple TV view implementations (both Fabric and non-Fabric
Fixes #637 .
[iOS][Fixed] enable long press for Touchable/Pressable on Apple TV
Tested in a local Apple TV project.

fix: [Apple TV] enable long press for Touchable/Pressable

---

README.md
packages/react-native/template/metro.config.js

Provide instructions and an example Metro config (in the template) for developers who need to support TV-specific file extensions (file.tv.tsx, etc.)
Closes #630 .
[General][Added] Instructions for TV-specific file extensions
Tested in multiple local projects.

feat: README and example for TV-specific file extensions

---

packages/react-native/React/CoreModules/RCTDeviceInfo.mm
packages/react-native/React/CoreModules/RCTRedBox.mm

When the cell is focused on the Error screen, the white text is hard to read on a light background. Changing the text color to black when the cell is in focus can enhance the text's readability.
And, fixing an error where the RNTester app fails to compile:
> [!CAUTION]
> RCTDeviceInfo.mm:107:56 'UIApplicationDidChangeStatusBarOrientationNotification' is unavailable: not available on tvOS
| Xcode Screenshot |
| - |
|<img width="1493" alt="Screenshot 2024-02-02 at 8 26 31 PM" src="https://github.com/react-native-tvos/react-native-tvos/assets/3449816/28025c72-1497-42db-b5e1-f86958d6be72">|
[IOS][FIXED] - Readability of text when Error message box is focused (tvOS)
[IOS][FIXED] - Compile error in RNTester app (tvOS)
Tested the change using the RNTester app and a newly created app. After the …

Improve reability of Error cell when focused (tvOS)

---

packages/rn-tester/js/RNTesterAppShared.js
packages/rn-tester/js/components/RNTesterNavbar.js

Makes navigating the RNTester app much simpler and more reliable on TV.
[General] [Internal] Remove absolute positioning in RNTester header for TV

chore: Remove absolute position in RNTester header on TV

---

packages/react-native/React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.mm
packages/rn-tester/js/examples/TVTextScrollView/TVTextScrollViewExample.js

When upstreaming [TVTextScrollView patch](https://github.com/react-native-tvos/react-native-tvos/pull/648) last month, we found that TVTextScrollView was not implemented at all for new architecture.
This PR adds swipe and focus handling in `RCTScrollViewComponentView` class (similar to `RCTScrollView`)
- [tvOS] [Fixed] - make TVTextScrollView component working when New Architecture is enabled
1. Go to tvOS `rn-tester` project and install pods with `RCT_NEW_ARCH_ENABLED=1` env
2. Run the RNTester app and go to `TVTextScrollViewExample`
3. Check that scrollviews can be scrolled using tv remote with swipes or dpad buttons

feat: implement <TVTextScrollView /> for New Architecture

---

README.md
packages/rn-tester/js/examples/FlatList/FlatList-additionalRenderRegions.js
packages/rn-tester/js/examples/FlatList/FlatListExampleIndex.js
packages/virtualized-lists/Lists/VirtualizedList.d.ts
packages/virtualized-lists/Lists/VirtualizedList.js
packages/virtualized-lists/Lists/VirtualizedListProps.js

This PR implements the feature requested in https://github.com/react-native-tvos/react-native-tvos/discussions/663.
Introduces `additionalRenderRegions` prop for `VirtualizedList` that accepts `{ first: number; last: number }[]` that allows you to define regions in the list that are not subject to virtualization, ensuring they are always rendered. This is particularly useful for preventing blank areas in critical parts of the list.
https://github.com/react-native-tvos/react-native-tvos/assets/22980987/9e10cf21-e942-4482-bf86-7d72fe1556be
https://github.com/react-native-tvos/react-native-tvos/assets/22980987/2c6c636b-bee0-42a9-9858-364527d7e9e9
[GENERAL] [ADDED] - `additionalRenderRegions` feature implemented for `VirtualizedList`.
Launch `RNTesterApp`
Navigate to `FlatList` section in …

feat: implement additionalRenderRegions feature

---

README.md
packages/react-native/Libraries/Components/TV/TVFocusGuideView.js
packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
packages/react-native/React/Views/RCTTVView.m
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java
packages/rn-tester/js/examples/TVFocusGuide/TVFocusGuideAutoFocusExample.js

Currently, disabling focus for view and its children is impossible. It is possible only by setting disabled for all touchable/pressable/buttons inside the view.
From the developer's perspective, I would love to have a prop that could be set for the parent view and will make all children not focusable.
In this PR I fixed the `focusable` prop in TVFocusGuideView that should block focus also for subviews of `TVFocusGuideView`
```
- [General][Fixed] - focusable prop in TVFocusGuideView blocks focus also for its subviews
```
It should be tested on both Android TV and tvOS platforms and both architectures.
I added a Row in `TVFocusGuide autoFocus example` with this prop. The focus engine should omit this whole row as in the videos below …

fix: TVFocusGuideView focusable prop set to false prevent focusing for all subviews

---

packages/react-native/React/Base/RCTTVNavigationEventNotification.h
packages/react-native/React/Base/RCTTVNavigationEventNotification.mm
packages/react-native/React/Base/RCTTVNavigationEventNotificationConstants.h
packages/react-native/React/Base/RCTTVNavigationEventNotificationConstants.mm
packages/react-native/React/Base/RCTTVRemoteHandler.h
packages/react-native/React/Base/RCTTVRemoteHandler.m
packages/react-native/React/Base/RCTTVRemoteHandlerConstants.h
packages/react-native/React/Base/RCTTVRemoteHandlerConstants.mm
packages/react-native/React/CoreModules/RCTTVNavigationEventEmitter.mm
packages/react-native/React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.mm
packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
packages/react-native/React/Views/RCTTVView.m
packages/react-native/React/Views/ScrollView/RCTScrollView.m

Proposed fix for #687.
On tvOS, the `NavigationEventNotification` will post an `eventKeyAction` value on the payload. The intent is to send data similar to that of Android. Android's [getAction](https://developer.android.com/reference/android/view/KeyEvent#getAction()) sends an `eventKeyAction` with a value of 0 for key down and 1 for key up.
The fix also helps identify the two events being sent for long gestures. Currently, there is no way to identify a long gesture event as an up or down action.
[IOS][ADDED] - Added up and down`eventKeyAction` to tvOS navigation event notifications
After creating a TestApp, I logged events to the console and verified the `eventKeyAction`.
```javascript
const myTVEventHandler = evt => {
console.log(evt);
};
useTVEventHandler(myTVEventHandler);
```

fix: Add eventKeyAction to Apple NavigationEventNotification

---

packages/react-native/Libraries/Components/Pressable/Pressable.js
packages/react-native/Libraries/Components/Touchable/TVTouchable.js
packages/react-native/Libraries/Components/Touchable/TouchableHighlight.js
packages/react-native/Libraries/Components/Touchable/TouchableNativeFeedback.js
packages/react-native/Libraries/Components/Touchable/TouchableOpacity.js
packages/react-native/Libraries/Pressability/Pressability.js
packages/rn-tester/js/examples/TVEventHandler/TVEventHandlerExample.js

There has been special code in the `Touchable` components to ensure that Android TV does not fire duplicate `onPress` events for the same press of the DPad.
This problem has now been traced to the root cause, which was `onPress` events fired with empty events from the `onClick` handler in `Pressability`.
These have been suppressed for TV, and the Android special handling removed from the `Touchable` classes.
[Android][Fixed] Remove spurious onClick events for Android TV
The `TVEventHandlerExample` in RNTester has been modernized and expanded to show remote control events as well as events from `Touchable` and `Pressable` components.

fix: Remove spurious onClick events for Android TV

---

packages/react-native/Libraries/Components/Pressable/Pressable.js
packages/react-native/Libraries/Components/TV/TVEventHandler.js
packages/react-native/Libraries/Components/TV/TVFocusEventHandler.js
packages/react-native/Libraries/Components/TV/TVTextScrollView.js
packages/react-native/Libraries/Components/TV/tagForComponentOrHandle.js
packages/react-native/Libraries/Components/TV/useTVEventHandler.js
packages/react-native/Libraries/Components/Touchable/TVTouchable.js
packages/react-native/Libraries/Components/Touchable/Touchable.js
packages/react-native/Libraries/Components/Touchable/TouchableHighlight.js
packages/react-native/Libraries/Components/Touchable/TouchableOpacity.js
packages/react-native/Libraries/Renderer/implementations/ReactFabric-dev.js
packages/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js
packages/react-native/Libraries/Types/CoreEventTypes.d.ts
packages/react-native/Libraries/Types/CoreEventTypes.js
packages/react-native/Libraries/Utilities/BackHandler.ios.js

Backport the changes to `TVEventHandler` and `TVFocusEventHandler` that were done for 0.74 branch.
[General][Fixed] Fixes and improvements to the event handler and the focus event handler, and related modules.
RNTester and local test apps should still work correctly with no changes.

fix: Refactor TV event handler and focus handler for RNTV 0.73

---

packages/react-native/React/Base/RCTTVRemoteHandler.m
packages/rn-tester/js/RNTesterAppShared.js

Apply the fix suggested in #678 .
[iOS][Fixed] Remove menu key from TVEventControl enable/disable gesture handler cancels touches
Modified RNTester to remove the workaround for this issue.

fix: [Apple TV] remove menu key from enableGestureHandlerCancelsTouches

---

packages/virtualized-lists/Lists/VirtualizedList.js

Our change to add a `TVFocusGuideView` wrapper around `VirtualizedList` should not be applied to non-TV platforms. This fix reverts that change for the case where `Platform.isTV` is false.
Fixes https://github.com/storybookjs/react-native/issues/568
[General][Fixed] Layout issue for VirtualizedList for non-TV platforms
See the Storybook issue above for a way to verify the fix.
TV projects should still work unchanged, and TV tests should still pass.

fix: Storybook virtualized list layout issue for non-TV platforms

---

packages/react-native/React/Fabric/Mounting/ComponentViews/Modal/RCTFabricModalHostViewController.h
packages/react-native/React/Fabric/Mounting/ComponentViews/Modal/RCTFabricModalHostViewController.mm
packages/react-native/React/Fabric/Mounting/ComponentViews/Modal/RCTModalHostViewComponentView.mm
packages/react-native/React/Views/RCTModalHostViewController.m

On Apple TV, the `Modal` component would dismiss via a menu key press, but the expected callbacks like `onRequestClose` and `onDismiss` were not being called, leaving the app in an unusable state.
Found that the needed view controller methods were missing from the modal view controller after the merge from 0.72 to 0.73. Restored those methods, and also fixed up the corresponding event handlers and view controller methods in the Fabric implementation.
Fixes #705 
[Apple TV][Fixed] Modal dismiss with menu key
Tested with the code submitted in #705 . For Fabric, that code should call `setShowModal(false)` in either the `onRequestClose` or `onDismiss` handler, as recommended in React Native docs for the `Modal` component.

fix: [Apple TV] restore missing event handlers in Modal

---

packages/react-native/types/__typetests__/tv-only.tsx
packages/react-native/types/public/ReactNativeTVTypes.d.ts

TS libdefs. isn't correct after merging: https://github.com/react-native-tvos/react-native-tvos/commit/dbbe0c2605434805ece24bd98aaa4da5767c1ee7 
https://github.com/react-native-tvos/react-native-tvos/blob/6d1eb49c20b8cbae9ec51ea332c13e8799bb619f/packages/react-native/Libraries/Components/TV/TVEventHandler.js#L21-L43
[GENERAL] [CHANGED] - [Typescript] Update `TVEventHandler` types to reflect the latest implementation
...

chore: [Typescript] Update `TVEventHandler` types to reflect the latest implementation

---

packages/react-native/React/Views/ScrollView/RCTScrollView.m

Fixes #726.
This PR prevents a scroll view from scrolling when disabled while the user swipes horizontally or vertically on Apple TV.
- Rename methods to scroll to vertical & horizontal offset. The scroll to vertical & horizontal offset methods are called when swiping and during focus updates. So, renaming methods to be more generic.
- Prevent horizontal or vertical scrolling when swiping & scrolling disabled
[IOS][FIXED] - Prevent ScrollView from scrolling when disabled.
Changes can be tested in the following branch:
[react-native-tvos-scrolling-bug/patch](https://github.com/cgoldsby/react-native-tvos-scrolling-bug/tree/patch)
```
cd react-native-tvos-scrolling-bug
yarn
yarn tvos
```
In the example app, the User can enable scrolling, vertical and horizontal layout, and short and long …

Fix - [Apple TV] TVTextScrollView is scrollable when scrollEnabled={false}

---

packages/react-native/types/public/ReactNativeTVTypes.d.ts

Fix #732 (a casing error in TV types)
[General][Fixed] Correct casing error in TV types
- Check that TS errors reported by VSCode in an application project have been removed.

fix: velocityX/velocityY TS types

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactAndroidHWInputDeviceHelper.java

Added some of the missing `KeyEvent` handlers for Android based on [this reference](https://developer.android.com/reference/android/view/KeyEvent) which makes possible to access them via `TVEventHandler`
[ANDROID] [CHANGED] - Add additional KeyEvents for HWInputDeviceHelper

Add additional KeyEvents for HWInputDeviceHelper

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/core/ReactAndroidHWInputDeviceHelper.java

Added three new long press KeyEvent handlers for Android : longPlayPause, longRewind and longFastForward. They can be useful in applications with video player to better control the stream.
They avoid to use modify the tweak with ReactFeatureFlags.enableKeyDownEvents = true and deal with the development of a new JS long press event for those key events.
longPlayPause key event is used in some application to start over a live stream (get back from the beginning)
[ANDROID] [CHANGED] - Add additional long press KeyEvents for HWInputDeviceHelper

 Add additional long press KeyEvents for HWInputDeviceHelper

---

packages/react-native/Libraries/Components/Pressable/Pressable.js
packages/rn-tester/js/examples/TVEventHandler/TVEventHandlerExample.js

Fixes Pressable regression in #744.
[General][Fixed] Fix Pressable onPress() events when style and children are not in functional form
See test app mentioned in #744. New test case added to RNTester in TVEventHandlerExample.

fix: Pressable regression in 0.74.2-0

---

packages/rn-tester/js/components/RNTesterNavbar.js

I found it not possible to navigate among the different tabs within the RNTester App when using this repository. The changes in this PR address this issue, allowing navigation between the content of the two different tabs.
https://github.com/user-attachments/assets/4a704df2-8590-490a-92a0-1da93a82457f
https://github.com/user-attachments/assets/a365b63f-bbf4-4895-bc3d-9f840fb96979
- [FIXED] Utilize TVFocusGuideView to enable navigation between tabs.
- [ADDED] Visually differentiate the tab in focus with a custom style.

RNTester: Interactive Navigation Bar

---

packages/react-native/types/public/ReactNativeTVTypes.d.ts

`tvFocusable` - property tvFocusable does not exist on type ViewProps
but I see usage in code base: https://github.com/search?q=repo%3Areact-native-tvos%2Freact-native-tvos%20tvFocusable&type=code
[GENERAL] [ADDED] - [Typescript] Add `tvFocusable` prop to view props
...

Add missing `tvFocusable` type in ViewProps

---

packages/react-native/Libraries/Components/TV/TVViewPropTypes.js
packages/react-native/Libraries/NativeComponent/TVViewConfig.js
packages/react-native/ReactCommon/react/renderer/components/view/BaseViewProps.cpp

Fix typos in prop types that were breaking autofocus on Apple TV when Fabric (bridgeless) was enabled.
Fixes #718
[iOS][Fixed] Enable TVFocusGuideView autoFocus in Fabric for Apple TV
RNTester TVFocusGuideView autoFocus test should work.

fix(iOS): Fix focus guide autofocus for Apple TV in Fabric

---

README-core.md
README.md

- Merge 0.75 changes from the core repo into `README-core.md`
- Changes to the TV `README.md`:
- Recommend Expo for new projects
- `create-react-native-app` section removed (no longer supported)
- New section on creating a new project with the new TV template (derived from the [community template](https://github.com/react-native-community/template))
- Remove outdated text
- Update example on using `TVEventHandler` directly in a class-based component

[docs] Update README for 0.75

---

packages/react-native/Libraries/Components/Pressable/Pressable.js

TV controls such as `Touchable*` and `Pressable` already support the `focus:` NativeWind style modifier. This change allows `Pressable` to support the `active:` NativeWind style modifier on TV.
See https://www.nativewind.dev/v4/core-concepts/states#hover-focus-and-active-
(This does not add `active:` support for the `Touchable*` components.)

feat: Add NativeWind support to Pressable

---

packages/react-native/Libraries/Components/Pressable/useAndroidRippleForView.js

Fixes an issue where `onPressIn` and `onPressOut` may not have `nativeEvent` properties.

fix: issue with onPressIn and Android ripple

---

packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
packages/react-native/React/Views/RCTTVView.m

Unset focus guides when changing the nextFocus prop back to undefined

fix: unset nextFocus guides when prop set to undefined

---

README.md
packages/react-native/Libraries/Components/Pressable/Pressable.js
packages/react-native/Libraries/Types/CoreEventTypes.d.ts
packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap
packages/rn-tester/js/examples/TVEventHandler/TVEventHandlerExample.js

- README changes
- Need to add `onFocusCapture`, `onBlurCapture` to `Pressable` props
- Focus, blur and press events should be allowed to have targets in Typescript definition
Screenshot from modified demo:

Native events: README changes, TVEventHandlerExample, other changes

---

packages/react-native/Libraries/Components/Pressable/Pressable.d.ts
packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
packages/react-native/React/Views/RCTTVView.m
packages/react-native/types/public/ReactNativeTVTypes.d.ts

Now that we are generating `pressIn` and `pressOut` events natively, the press magnification animation in Apple TV parallax properties needs to be coordinated with these events, and not use its own delay and occur after the native events are emitted.
After this fix, the animation is smooth and coordinated with the style changes initiated by the press events.
Also fixed up the Typescript type for the parallax properties and made sure they are included in `Pressable` prop types.
Before:
https://github.com/user-attachments/assets/9a0c25d2-6d7e-47d3-9ec9-fc3ef8264c81
After:
https://github.com/user-attachments/assets/a98de4f6-c26f-4af4-ac9f-f7d5d30f7103

fix: coordinate tvOS press animations with native events

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.kt

The computed property `androidHWInputDeviceHelper` previously used a custom getter that created a new instance of `ReactAndroidHWInputDeviceHelper` each time it was accessed. This behavior led to a new instance being created with every key press, causing issues with maintaining state, such as tracking the last focused button.
By switching to a `by lazy` initialization approach, `androidHWInputDeviceHelper` is now instantiated only once upon its first access, preserving its state across key presses. This ensures that the "select" key functions correctly by retaining focus information across button interactions.

Optimize androidHWInputDeviceHelper to use lazy initialization

---

packages/react-native/React/Base/RCTTVRemoteHandler.m
packages/react-native/React/Base/RCTTVRemoteSelectHandler.h
packages/react-native/React/Base/RCTTVRemoteSelectHandler.m
packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.h
packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
packages/react-native/React/Views/RCTTVView.h
packages/react-native/React/Views/RCTTVView.m
packages/rn-tester/js/examples/TVEventHandler/TVEventHandlerExample.js

The introduction of fully native focus/blur/pressIn/pressOut in #813 led to an inconsistency in the behavior of the TV event handler. On Android TV, the `select` and `longSelect` events are still sent to the handler. On Apple TV, they are missing.
Root cause was interference between the select gesture recognizer in the views, and the one in `RCTTVRemoteHandler`.
Solution:
- Remove handling of select and longSelect from `RCTTVRemoteHandler`
- Create a new class, `RCTTVRemoteSelectHandler`, that has the select and longSelect gesture recognizers, and calls delegate methods in the views when these gestures start and finish
- The new class is used by both Fabric and non-Fabric views, to avoid code duplication.
Before:
After:

fix: restore TV event handler select/longSelect for tvOS

---

packages/react-native/React/Views/RCTTVView.h
packages/react-native/React/Views/RCTView.h

Fixes #833 .
This problem is specific to apps running in old non-Fabric architecture. It occurs because in the old architecture implementation, some views (TextInput, ScrollView) do not inherit from the TV-specific RCTTVVIew class.
For correct behavior and to avoid other regressions, I've moved the handler properties to RCTView.

fix: TextInput regression with new native events and old arch

---

packages/react-native/ReactAndroid/src/test/java/com/facebook/react/RootViewTest.kt

The `testCheckForKeyboardEvents` unit test is failing with a `NullPointerException` in `ReactAndroidHWInputDeviceHelper.java`.  
```shell
RootViewTest > testCheckForKeyboardEvents FAILED  
java.lang.NullPointerException at ReactAndroidHWInputDeviceHelper.java:233  
> Task :packages:react-native:ReactAndroid:testDebugUnitTest FAILED  
311 tests completed, 1 failed, 7 skipped  
FAILURE: Build failed with an exception.  
```
The failure occurs because the `ReactContext` is not properly mocked during the test execution, causing the `getJSModule` method to return `null`. This leads to a `NullPointerException` when attempting to emit events.  
The test has been updated to properly mock the `ReactContext` and the `RCTDeviceEventEmitter` module, ensuring that event emissions are handled correctly …

Fix broken Android RootViewTest

---

packages/react-native/Libraries/Components/Pressable/Pressable.d.ts
packages/react-native/types/public/ReactNativeTVTypes.d.ts

Add missing types to focus destinations, and unify types.
Fixes #844

fix: TS types for TV focus destinations

---

packages/react-native/React/Base/RCTConvert.mm

Running into the issue that the Modal isn't transparent, like described #831 also.
This fixes that. Android already works like expected.
Without the fix it shows the background:
https://github.com/user-attachments/assets/39c7abe9-b11c-4bbf-9c2e-f32542626486
With the fix the background is transparent, like expected:
https://github.com/user-attachments/assets/9b8a0b60-8bfe-4768-b92a-32f3196d84e5
Code snippet to test:
```tsx
const [showModal, setShowModal] = useState(false);
return (
<View style={{ flex: 1 }}>
<View
style={{
flex: 1,
backgroundColor: 'gray',
alignItems: 'center',
justifyContent: 'center',
}}
>
<TouchableHighlight
style={{
padding: 10,
}}
underlayColor="red"
onPress={() => setShowModal(true)}
>
<Text>Show Modal</Text>
</TouchableHighlight>
</View>
<Modal
transparent={true} …
```

fix: allow UIModalPresentationOverFullScreen on transparent Modal

---

packages/react-native/Libraries/Pressability/Pressability.js
packages/react-native/Libraries/Pressability/__tests__/Pressability-test.js

This PR fixes incorrect handling of the `disabled` prop in the `Pressability` class. The `onPressIn` and `onPressOut` handlers now correctly exit early when `disabled` is set to `true`, ensuring that no unintended interactions occur.
I think this mistake slipped in during the #813 refactor.

fix: `disabled` prop - invert condition in Pressability.js event handlers

---

packages/rn-tester/js/examples/Modal/ModalOnShow.js

This PR addresses an issue where the Modal background color was not rendering correctly in the 0.77.0-rc5 release candidate of react-native-tvos.
Details
- The issue was reported in [this discussion](https://github.com/react-native-tvos/react-native-tvos/discussions/851#discussioncomment-11733423).
| Before | After |
| - | - |
|![400142328-18adfcd1-beb2-4200-ad8e-d4d29d4995f6](https://github.com/user-attachments/assets/017b619b-b879-4f62-9559-b21bdf4de82c)|![Screenshot_1736187184](https://github.com/user-attachments/assets/680e89d3-cc23-42a2-ac07-88ec9011dd0c)|

[Release 0.77.0-0rc5] Set RNTester modal background color

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactDelegate.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.kt
packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterActivity.kt
packages/rn-tester/js/examples/Modal/ModalOnShow.js

---
This pull request addresses the key events propagation issue reported in #829 in the `react-native-tvos` repository. The fix incorporates feedback from the original issue discussion and resolves the problem where `ACTION_DOWN` key events were not properly propagated to the Android app's main activity modals.
---
- Added a condition to delegate `ACTION_DOWN` key events to `onDialogKeyDown` when a modal is open.
- Updated handling of `ACTION_UP` key events to be delegated to `onDialogKeyUp`.
- Tries to incorporate feedback from the original issue discussion.
---
1. Clone the repository:
```bash
gh repo clone cgoldsby/react-native-tvos
```
2. Checkout the branch `modalFix-test`:
```bash
git checkout modalFix-test
```
3. Install dependencies:
```bash
yarn
```
4. Build and run the project …

[Release 0.77.0-0rc5] Fix Key Events Propagation Issue on Android TV's Modals #829

---

packages/react-native/Libraries/Components/TV/TVFocusGuideView.js
packages/react-native/Libraries/Components/View/ViewPropTypes.d.ts

After running the lint task:
```
yarn ; yarn lint
$ eslint .
../react-native-tvos/packages/react-native/Libraries/Components/TV/TVFocusGuideView.js
11:14  warning  'HostComponent' is defined but never used  no-unused-vars
✖ 1 problem (0 errors, 1 warning)
✨  Done in 9.77s.
````
This warning is displayed in my private project when I ran `npx tsc`. I've updated the `onBlur` and `onFocus` props to use the native events.
```
node_modules/react-native/Libraries/Components/View/ViewPropTypes.d.ts:130:18 - error TS2430: Interface 'ViewProps' incorrectly extends interface 'FocusEvents'.
Types of property 'onFocus' are incompatible.
Type 'BubblingEventHandler<Event>' is not assignable to type '(event: FocusEvent) => void'.
Types of parameters 'event' and 'event' are incompatible.
Type 'FocusEvent' …
```

fix: minor typescript fixes

---

packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
packages/react-native/React/Views/RCTTVView.m
packages/rn-tester/js/examples/TVEventHandler/TVEventHandlerExample.js

This PR adresses issue #867 after the investigation detailed in the comments. It should probably be backported to 0.76 since the bubbling focus event feature was introduced in this version

fix: TVFocusGuide extra onBlur trigger on focus

---

packages/react-native/Libraries/Pressability/Pressability.js
packages/react-native/Libraries/Pressability/__tests__/Pressability-test.js

#856 is part of the release [0.76.6 release](https://github.com/react-native-tvos/react-native-tvos/releases/tag/v0.76.6-0) but did not make it into 0.77.0. cc: @psysize
```
git cherry-pick 5eb839d958995e0c7a2b48ec07e3ca994af4c09c
```

fix: [Regression] invert disabled condition in Pressability event handlers and add tests (#856)

---

packages/react-native/package.json

Customize the repo, homepage, and keywords in the react-native package.json

fix: react-native-tvos NPM metadata

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.kt

This PR fixes #759.
Apparently, prop setter functions can (and do) get called whether their value actually changed or not. The weird thing is, this property only applies if a given property changes **at least once** after the initial creation of a component. If it never changes after the initial render, it's all good. So, if you set your `hasTVPreferredFocus` to true on a component and never change it on runtime, it's cool, you don't experience the issue. This whole thing feels like a bug and I'd like dive deeper (if I had time) on this one but it seems like the way things really work at the moment.
I applied more of a band-aid to mitigate this issue. I basically keep a "current value" state for `hasTVPreferredFocus` and run a basic conditional on it to understand whether the value …

fix: make hasTVPreferredFocus work properly on the new arch

---

packages/react-native/ReactAndroid/src/main/AndroidManifest.xml
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactActivityDelegate.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactFragment.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/devsupport/DebugOverlayController.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/i18nmanager/I18nManagerModule.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/permissions/PermissionsModule.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/BackgroundStyleApplicator.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModuleConstantsHelper.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/drawable/BackgroundDrawable.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/drawable/BorderDrawable.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/drawable/CSSBackgroundDrawable.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/drawable/CompositeBackgroundDrawable.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/drawable/Drawable.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/drawable/LayerDrawable.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/drawable/OutlineDrawable.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactBaseTextShadowNode.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextShadowNode.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextView.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/text/TextLayoutManager.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputLocalData.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputShadowNode.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactDrawableHelper.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.kt
packages/react-native/gradle/libs.versions.toml

This PR adds Android API 22 support to React Native 0.77 version.
There are a lot of old Android devices in the TV hardware market still in use. Just like people are not replacing their TVs that often, they tend to not replace their smart TV hardwares. It's important to be able to provide service to those devices, if you want/need to.
Most of the code changes in this PR are based on the old codes where RN was officially supporting older Android versions. You can go simply go check 0.73 branch, which is the latest RN version supporting API 22, for a given file to validate the approaches if you'd like. Although, there are a couple of exceptions needs explaining.
The changes in [CompositeBackgroundDrawable.kt](https://github.com/react-native-tvos/react-native-tvos/compare/tvos-v0.77.0...feat/ …

Add Android API 22 support to version 0.77

---

README.md

A couple of links in the README are outdated. This small PR updates them to their current locations (notably the `metro.config.js` example).

[docs] Update broken links in README

---

packages/react-native/React/Base/RCTRootView.h
packages/react-native/React/Base/RCTRootView.m
packages/react-native/React/Base/RCTRootViewInternal.h
packages/react-native/React/Base/RCTTVRemoteSelectHandler.m
packages/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceHostingProxyRootView.h
packages/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceHostingProxyRootView.mm

Fixes #904 .
We add a RCTTVRemoteSelectHandler to the root view, and ensure that its gesture recognizer does not run if there is a pressable or touchable present with its own handler.

[Apple TV] Fix for missing select events

---

packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
packages/react-native/React/Views/RCTTVView.m

This ensures the same order of focus&blur events for global notifier and direct event listeners. Currently, it's 50/50 for onFocus/onBlur order, while global NSNotification based events are always in deterministic order (onFocus(new) -> onBlur(old)).
Deterministic order makes it easier to handle in custom JS focus mechanisms.
Also, placing onFocus/Blur in coordinatedAnimated ensures visual feedback (parallax animation) is coordinated with onFocus/onBlur listeners making the animation & focus changes more smooth looking.

[Apple TV] Synchronize focus notifications and direct view events

---

tools/rntv-workflows/.eas/build/build-rntester-android.yml
tools/rntv-workflows/app.json
tools/rntv-workflows/build-rntester-android.sh
tools/rntv-workflows/eas.json

Add scripts and EAS build profile for building Android RNTester artifact on pull requests, similar to PR #930 for Apple TV.
Builds will now be invoked with custom labels `eas-build-android:rntester` and `eas-build-ios:rntester`.

[CI][Android] Generate RNTester artifact on PRs and pushes

---

packages/react-native/scripts/cocoapods/utils.rb

In multitarget project, CocoaPods generates multiple pod instances for each platform (and/or OS version, swift version etc). See more: https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/target/pod_target.rb
Take a following Podfile as an example:
```
(...)
target 'PlatformPodRepro-iphone' do
platform :ios, '16.0'
config = use_native_modules!
use_react_native!(
:path => "../node_modules/react-native",
:app_path => "#{Pod::Config.instance.installation_root}/.."
)
end
target 'PlatformPodRepro-appletv' do
platform :tvos, '16.0'
config = use_native_modules!
use_react_native!(
:path => "../node_modules/react-native",
:app_path => "#{Pod::Config.instance.installation_root}/.."
)
end
post_install do |installer|
react_native_post_install(
installer,
"../node_modules/react-native", …
```

Fix js debugging in multitarget project

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollView.java

Native Android ScrollView TV changes from #321 have disappeared since 0.77.0-0 (see `ReactScrollView.java` in [0.76.9-0](https://github.com/react-native-tvos/react-native-tvos/blob/9930ee9dbe09b760ca4e072b66fa526397ad477b/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollView.java#L416) vs [0.77.0-0](https://github.com/react-native-tvos/react-native-tvos/blob/fad8580bbe478661208ef72aa0ddceedd23dd3fb/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollView.java#L402)). It makes disabled vertical scroll views scroll on children focus on Android, unlike tvOS.
The changes were reverted in commit [Back out TV changes in native Android scroll view](https://github.com/react-native-tvos/react-native-tvos/commit/0025b …

Regression since 0.77 : fix vertical scroll views auto scrolling to children on Android when scroll is disabled

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactHorizontalScrollView.java

Fixes #940 for 0.80.0
[ANDROID] [FIXED] - make `scrollEnabled` work properly for HorizontalScrollView

[Android] [0.80]  fix: make `scrollEnabled` work properly for HorizontalScrollView

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactHorizontalScrollView.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactScrollView.java

Fixes #940 for 0.78.0
[ANDROID] [FIXED] - make `scrollEnabled` work properly for ScrollView and HorizontalScrollView

[Android] [0.78]  fix: make `scrollEnabled` work properly for ScrollView and HorizontalScrollView

---

packages/react-native/Libraries/Components/TV/TVFocusGuideView.js
packages/react-native/Libraries/Components/View/View.js

When using a callback function React and React Native only call that function when the node is mounted, or the callback handle has been updated. The tvos code changes this behaviour and calls it on each render.
But because of the `setAndForwardRef` helper that is used, the handle changes each render, and thus calling the callback ref each render. First with the `null` value and then with (the same) node ref again.
Basic test, which on and Expo build should only show the log once, but on an Expo TV build shows the log each second.
```ts
import {Text, View} from 'react-native';
import {useCallback, useEffect, useState} from "react";
export default function App() {
return <View>
<MyView />
</View>
}
const MyView = () => {
const [focused, setFocused] = useState(false);
const callbackRef = …
```

Fix callback ref triggering on each render

---

tools/rntv-workflows/.eas/build/build-android-artifacts.yml
tools/rntv-workflows/src/cut-release-branch.ts
tools/rntv-workflows/src/download-hermesc.ts

The RNTV release needs to include the `hermesc` artifacts built by core CI for Mac, Windows, and Linux.
- Tested against a preliminary 0.81 release
- Release CI should download the hermesc artifacts and include them in generated react-native-tvos NPM tarball.

TV: Android artifact build should download hermesc from core build

---

packages/react-native/React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.mm
packages/react-native/React/Views/ScrollView/RCTScrollView.h
packages/react-native/React/Views/ScrollView/RCTScrollView.m
packages/react-native/React/Views/ScrollView/RCTScrollViewManager.m
packages/react-native/ReactCommon/react/renderer/components/scrollview/BaseScrollViewProps.cpp
packages/react-native/ReactCommon/react/renderer/components/scrollview/BaseScrollViewProps.h

This is an adjustment to #568 . This repo allows building apps for both iOS and tvOS. We would like iOS builds to be interoperable with the packager and JS bundles from the RN core repo.
Here, we wrap references to `showsScrollIndex` so that they are only compiled for tvOS, not iOS, where they are not needed. This keeps the iOS native code compatible with the core repo, which does not have the `showsScrollIndex` view prop.
- CI should pass
- The RNTester iOS app built by CI should work with the packager from the RN core repo of the same version (currently testing against core version 0.81.0-rc.2)
- The RNTester iOS app should pass the RN core repo's Maestro tests

TV: showsScrollIndex should only be active on tvOS

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java

I found three different edge cases in the focus logic that leads to endless `requestFocus` loops on Android side. This behavior was crashing the application with an impossible to understand and debug error. I fixed those cases by restructuring the code a bit.
[ANDROID] [FIXED] - Improve TVFocusGuideView stability.

fix: prevent focus loops
